name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required to allow pushing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          snake_color: 'blue'
          days_count: 0

      - name: Commit and push generated snake
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: output
          message: 'Generate Contribution Snake'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Pass token explicitly
